[org 0x0100]            ; .COM file format

start:
    ; Set video mode 13h (320x200, 256 colors)
    mov ax, 0x0013
    int 0x10

    ; Load the background palette into the VGA DAC
    call load_palette_background

    ; Load and display the background
    call display_background

    ; Wait for a key press before exiting
    mov ah, 0x00
    int 0x16

    ; Exit to DOS
    mov ax, 0x4C00
    int 0x21

;=============================
; Function: load_palette_background
; Loads the background palette into VGA DAC registers
;=============================
load_palette_background:
    mov dx, 0x03C8          ; Set starting color index (0)
    xor al, al            ; Start at color 0
    out dx, al
    inc dx                   ; Move to DAC data register (0x03C9)

    ; Load all 256 colors (each color has 3 components: R, G, B)
    mov cx, 256 * 3          ; 256 colors * 3 components (RGB)
    mov si, palette_data_background ; SI points to the palette data

load_palette_loop_background:
    lodsb                    ; Load the next palette value into AL
    out dx, al               ; Send the value to the DAC
    loop load_palette_loop_background    ; Repeat for all 256 colors
    ret

;=============================
; Function: display_background
; Displays the full-screen background image in video memory
;=============================
display_background:
    mov ax, 0xA000           ; Set ES to video memory segment
    mov es, ax
    mov si, pixel_data_background ; SI points to the pixel data

    ; Set the position to (0, 0) in video memory
    mov di, 0  ; DI = x + y * 320 (offset in video memory)
    
    mov cx, 200               ; 200 rows to display (for 320x200 resolution)

display_row_background:
    push cx
    mov cx, 320               ; 320 pixels per row (since the screen is 320 pixels wide)

display_pixel_background:
    lodsb                    ; Load a byte (pixel color index) from pixel_data_background
    stosb                    ; Store the byte in video memory (A000h:DI)
    loop display_pixel_background   ; Repeat for all 320 pixels in the row

    pop cx
    loop display_row_background     ; Repeat for all 200 rows
    ret

;=============================
; Data Section
;=============================
%include 'background.asm'     ; Include the pixel data and palette generated by Python
